service: quakejs
image: neonwatty/quakejs
servers:
  web:
    - 35.94.171.93
proxy:
  ssl: true
  host: ytgiphy.xyz
  # Proxy connects to your container on port 80 by default.
  # app_port: 3000

registry:
  server: ghcr.io
  username: neonwatty
  password:
    - GITHUB_REGISTRY_TOKEN

# Configure builder setup.
builder:
  arch: amd64

# Use a different ssh user than root
ssh:
  user: ubuntu
